version: "3.7"
services:
  web:
    image: nginx
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
    ports:
    - "1515:80"
    networks:
    - webserver
networks:
  webserver: